server:
  port: 8080
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ #告诉服务提供者要把服务注册到哪儿
  instance:
    prefer-ip-address: true #显示客户端真实ip
spring:
  application:
    name: user-service
  rabbitmq:
    host: 10.0.12.74
    port: 5672
    password: admin
    username: admin
feign:
  hystrix:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
