spring:
  rabbitmq:
    host: 10.0.12.74
    port: 5672
    password: admin
    username: admin
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
