app:
  env: demo
server:
  port: 10001

logging:
  level:
    org.springframework.cloud.sleuth: debug

spring:
  application:
    name: gateway-server
#  sleuth:
#    sampler:
#     probability: 1.0
#  zipkin:
#     base-url: http://10.0.12.76:9411/
  redis:
    host: 10.0.12.74
    port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          predicates:
            - Path=/global
          filters:
            - MyDefine=zzk
          uri: http://localhost:10001/hello

        - id: ms-oauth2-service
          predicates:
            - Path=/passport/oauth/**
          uri: lb://ms-oauth2-server-${app.env}

        - id: api-dmp-task
          predicates:
            - Path=/dmp/task/**
          uri: lb://srv-dmp-task-${app.env}

        - id: api-dmp-hive
          predicates:
            - Path=/dmp/hive/**
          uri: lb://srv-dmp-datasource-${app.env}

        - id: api-dmp-datasource
          predicates:
            - Path=/dmp/datasources/**
          uri: lb://srv-dmp-datasource-${app.env}

        - id: api-dmp-model
          predicates:
            - Path=/dmp/model/**
          uri: lb://srv-dmp-model-${app.env}

        - id: api-dmp-manager
          predicates:
            - Path=/dmp/manager/**
          uri: lb://srv-dmp-manager-${app.env}

        - id: api-dmp-experiment
          predicates:
            - Path=/dmp/**
          uri: lb://srv-dmp-experiment-${app.env}

        - id: order-service
          predicates:
            - Path=/pd-mall/**
          filters:
            - StripPrefix=1
            - MyDefine=zzk
          uri: lb://order-service
        - id: lb_route
          predicates:
            - Path=/lb/**
          filters:
            - StripPrefix=1
          uri: lb://order-service
        - id: redis_rate_limiter
          predicates:
            - Path=/ratelimiter/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                keyResolver: '#{@ipAddressKeyResolver}'
                deny-empty-key: true
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 2
          uri: lb://order-service







