server:
  port: 9090
spring:
  application:
    name: order-service
#  sleuth:
#    sampler:
#     probability: 1.0
#  zipkin:
#    base-url: http://10.0.12.76:9411/

  datasource:
    url: jdbc:mysql://10.0.12.72:3306/pd_mall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    password: C!Fr0ShoW9Nu
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.cloud.sleuth: debug